#Define Data Field
short HeaderMask 0x0FF 
short ProtocolVersion 1000
short PacketSize 115
short MessageType 0
float Steering 0x86[16:28] * 0.1 *(0x86[29] * -2 + 1)
float Brake 0x105[34:35] * 33.33
float Accel 0x105[48:55] * 0.4
float ParkingBrake 0x6D9[20] * -1 + 1.0
byte GearP 0x393[24:29] == 0x2? 1:0
byte GearR 0x393[24:29] == 0x3? 1:0
byte GearN 0x393[24:29] == 0x4? 1:0
byte GearD 0x393[24:29] == 0x25? 1:0
byte IgnitionOff 0
byte IgnitionACC 0x105[39] == 0x0? 1:0
byte IgnitionON 0x105[39] == 0x1? 1:0
byte IgnitionStart 0
byte IndicatorLeft 0
byte IndicatorRight 0
byte IndicatorHazard 0
float float1 0
float float2 0
float float3 0
float float4 0
float float5 0
float float6 0
float float7 0
float float8 0
float float9 0
float float10 0
int int1 0
int int2 0
int int3 0
int int4 0
int int5 0
int int6 0
int int7 0
int int8 0
int int9 0
int int10 0

#Target Info
Target 127.0.0.1
MyPort 8001
Port 8000
Period 2